In [ ]:
# Import required libraries and dependencies
import pandas as pd
import hvplot.pandas

In [2]:
# Import methods 
import sys
sys.path.append("../")
from methods.dataframe_methods import clean_columns

In [3]:
# Set column display options
pd.set_option("display.max_columns", None)

Unenployment rate by country 1991-2021

In [4]:
# Read the CSV file into a `pandas` DataFrame - Unemployment
unemployment_file = "https://raw.githubusercontent.com/kkruel8100/Crime-Analysis/main/resources/unemployment%20analysis.csv"
unemployment_df = pd.read_csv(unemployment_file, low_memory=False)

# Create a copy of the df
unemployment_copy = unemployment_df.copy()

# Clean the columns
cleaned_unemployment_copy = clean_columns(unemployment_copy)

# Display df head and info
display(cleaned_unemployment_copy.head())
display(cleaned_unemployment_copy.info())

,country_name,country_code,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Africa Eastern and Southern,AFE,7.80,7.84,7.85,7.84,7.83,7.84,7.86,7.81,7.79,7.72,7.73,7.96,7.79,7.31,7.12,6.99,6.74,6.27,6.32,6.87,6.75,6.56,6.45,6.41,6.49,6.61,6.71,6.73,6.91,7.56,8.11
1,Afghanistan,AFG,10.65,10.82,10.72,10.73,11.18,10.96,10.78,10.80,10.81,10.81,10.81,11.26,11.14,10.99,11.22,11.10,11.30,11.09,11.31,11.35,11.05,11.34,11.19,11.14,11.13,11.16,11.18,11.15,11.22,11.71,13.28
2,Africa Western and Central,AFW,4.42,4.53,4.55,4.54,4.53,4.57,4.60,4.66,4.86,4.92,4.87,4.78,4.75,4.73,4.73,4.65,4.63,4.60,4.58,4.55,4.55,4.64,4.41,4.69,4.63,5.57,6.02,6.04,6.06,6.77,6.84
3,Angola,AGO,4.21,4.21,4.23,4.16,4.11,4.10,4.09,4.07,4.05,4.03,4.00,3.96,3.96,3.92,3.88,3.86,3.82,3.79,3.78,9.43,7.36,7.35,7.37,7.37,7.39,7.41,7.41,7.42,7.42,8.33,8.53
4,Albania,ALB,10.31,30.01,25.26,20.84,14.61,13.93,16.88,20.05,20.84,19.03,18.58,17.90,16.99,16.31,15.97,15.63,15.97,13.06,13.67,14.09,13.48,13.38,15.87,18.05,17.19,15.42,13.62,12.30,11.47,13.33,11.82

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_name  235 non-null    object
 1   country_code  235 non-null    object
 2   1991          235 non-null    float64
 3   1992          235 non-null    float64
 4   1993          235 non-null    float64
 5   1994          235 non-null    float64
 6   1995          235 non-null    float64
 7   1996          235 non-null    float64
 8   1997          235 non-null    float64
 9   1998          235 non-null    float64
 10  1999          235 non-null    float64
 11  2000          235 non-null    float64
 12  2001          235 non-null    float64
 13  2002          235 non-null    float64
 14  2003          235 non-null    float64
 15  2004          235 non-null    float64
 16  2005          235 non-null    float64
 17  2006          235 non-null    float64
 18  2007          235 non-null    float64
 19  2008          235 non-null    float64
 20  2009          235 non-null    float64
 21  2010          235 non-null    float64
 22  2011          235 non-null    float64
 23  2012          235 non-null    float64
 24  2013          235 non-null    float64
 25  2014          235 non-null    float64
 26  2015          235 non-null    float64
 27  2016          235 non-null    float64
 28  2017          235 non-null    float64
 29  2018          235 non-null    float64
 30  2019          235 non-null    float64
 31  2020          235 non-null    float64
 32  2021          235 non-null    float64
dtypes: float64(31), object(2)
memory usage: 60.7+ KB

None

In [5]:
# Sort values and display tail
cleaned_unemployment_copy.sort_values("country_name", inplace=True)
cleaned_unemployment_copy.tail(20)

,country_name,country_code,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
215,Tunisia,TUN,15.65,15.58,15.83,15.86,15.94,15.83,15.94,15.61,15.21,14.94,14.40,14.55,14.51,14.23,12.87,12.51,12.36,12.44,13.29,13.05,18.33,17.63,15.93,15.06,15.16,15.56,15.33,15.46,15.13,16.59,16.82
216,Turkiye,TUR,8.21,8.51,8.96,8.58,7.64,6.63,6.84,6.89,7.69,6.50,8.38,10.36,10.54,10.84,10.64,8.72,8.87,9.71,12.55,10.66,8.80,8.15,8.73,9.88,10.24,10.84,10.82,10.89,13.67,13.11,13.39
207,Turkmenistan,TKM,1.40,1.50,1.50,4.70,8.30,10.30,11.00,12.20,12.70,11.54,10.68,9.75,8.99,8.19,7.50,6.61,5.76,4.95,4.00,4.00,4.09,4.09,4.11,4.14,4.14,4.17,4.20,4.23,4.27,4.95,5.08
218,Uganda,UGA,0.94,0.92,1.16,1.42,1.65,1.92,2.21,2.47,2.71,3.03,3.27,3.50,3.60,2.75,1.90,2.29,2.73,3.15,3.60,3.59,3.51,3.55,1.91,1.91,1.91,1.92,1.93,1.92,1.92,2.77,2.94
219,Ukraine,UKR,1.90,1.90,2.00,2.00,5.62,7.65,8.93,11.32,11.86,11.71,11.06,10.14,9.06,8.59,7.18,6.81,6.35,6.36,8.84,8.10,7.85,7.53,7.17,9.27,9.14,9.35,9.50,8.80,8.19,9.13,8.88
6,United Arab Emirates,ARE,1.87,1.84,1.85,1.81,1.80,1.90,1.98,2.14,2.22,2.25,2.49,2.65,2.75,2.91,3.12,2.94,2.87,2.74,2.68,2.48,2.30,2.18,2.04,1.91,1.77,1.64,2.46,2.35,2.23,3.19,3.36
71,United Kingdom,GBR,8.55,9.78,10.35,9.65,8.69,8.19,7.07,6.20,6.04,5.56,4.70,5.04,4.81,4.59,4.75,5.35,5.26,5.62,7.54,7.79,8.04,7.88,7.52,6.11,5.30,4.81,4.33,4.00,3.74,4.47,4.53
222,United States,USA,6.80,7.50,6.90,6.12,5.65,5.45,5.00,4.51,4.22,3.99,4.73,5.78,5.99,5.53,5.08,4.62,4.62,5.78,9.25,9.63,8.95,8.07,7.37,6.17,5.28,4.87,4.36,3.90,3.67,8.05,5.46
220,Upper middle income,UMC,3.82,3.87,4.19,4.62,5.01,5.18,5.34,5.61,5.76,5.52,5.77,6.05,6.22,6.01,5.93,5.70,5.45,5.49,5.99,5.67,5.54,5.48,5.49,5.49,5.66,5.90,5.93,5.77,6.00,6.76,6.76
221,Uruguay,URY,8.95,8.96,8.35,9.04,10.02,11.93,11.44,9.36,10.47,12.63,15.05,16.65,16.66,12.98,12.01,10.84,9.40,8.03,7.74,7.16,6.31,6.45,6.44,6.55,7.49,7.84,7.89,8.34,8.88,10.35,10.45
223,Uzbekistan,UZB,1.90,2.90,4.90,7.30,7.80,10.70,10.90,13.30,13.30,12.23,11.20,10.15,9.11,8.19,7.09,6.03,4.99,4.89,5.00,5.40,5.00,4.90,4.90,5.10,5.20,5.20,5.80,5.84,5.85,7.04,7.16
228,Vanuatu,VUT,1.68,1.69,1.73,1.59,1.74,1.72,1.68,1.76,1.78,1.69,1.88,1.92,1.74,1.75,1.73,1.68,1.79,1.75,1.81,1.85,1.81,1.85,1.86,1.81,1.86,1.78,1.75,1.81,1.80,2.12,2.18
225,"Venezuela, RB",VEN,9.45,7.69,6.60,8.56,10.24,11.77,11.16,11.15,14.53,13.99,13.04,16.17,16.78,15.07,10.66,8.61,7.28,6.25,6.10,7.11,6.90,6.60,7.54,6.86,6.08,5.32,5.05,5.02,5.10,6.63,6.41
227,Vietnam,VNM,2.09,1.91,1.97,1.93,1.90,1.93,2.87,2.29,2.33,2.26,2.76,2.12,2.25,2.14,2.10,2.09,2.03,1.93,1.74,1.11,1.00,1.03,1.32,1.26,1.85,1.85,1.87,1.16,2.04,2.39,2.17
226,Virgin Islands (U.S.),VIR,12.35,12.51,12.70,12.47,12.13,12.21,12.12,11.86,11.50,11.11,11.08,11.19,11.36,11.05,10.96,10.41,10.19,10.31,11.58,11.73,12.08,12.23,12.76,12.79,12.62,12.68,12.32,12.43,12.47,13.55,13.27
172,West Bank and Gaza,PSE,11.60,11.31,11.29,11.15,11.10,11.03,10.83,10.72,10.64,10.63,21.49,27.46,23.00,23.21,20.02,19.01,18.28,22.91,20.45,21.42,17.60,19.20,19.89,20.53,23.00,23.94,25.68,26.26,25.34,25.89,24.90
229,World,WLD,4.80,4.96,5.23,5.49,5.63,5.70,5.70,5.86,5.97,5.77,5.86,6.07,6.16,6.00,5.90,5.63,5.42,5.41,6.01,5.90,5.77,5.74,5.73,5.60,5.62,5.66,5.56,5.39,5.36,6.57,6.18
231,"Yemen, Rep.",YEM,8.32,8.31,8.35,8.34,8.96,9.59,10.20,10.81,11.46,11.56,11.71,11.84,11.97,12.10,12.21,12.37,12.49,12.62,12.75,12.83,13.23,13.17,13.27,13.47,13.77,13.43,13.30,13.15,13.06,13.39,13.57
233,Zambia,ZMB,18.90,19.37,19.70,18.43,16.81,15.30,13.64,12.00,12.44,12.93,13.51,14.12,14.69,15.30,15.90,13.24,10.59,7.93,10.56,13.19,10.55,7.85,8.61,9.36,10.13,10.87,11.63,12.01,12.52,12.85,13.03
234,Zimbabwe,ZWE,4.94,4.99,4.97,4.96,5.63,6.25,6.93,6.46,6.00,5.69,5.36,5.06,4.75,4.39,4.54,4.68,4.83,5.01,5.08,5.21,5.37,5.15,4.98,4.77,4.78,4.79,4.78,4.80,4.83,5.35,5.17

In [6]:
# Create US unemployment df and display
unemployment_us = cleaned_unemployment_copy.loc[cleaned_unemployment_copy["country_name"] == "United States"]
unemployment_us

,country_name,country_code,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
222,United States,USA,6.8,7.5,6.9,6.12,5.65,5.45,5.0,4.51,4.22,3.99,4.73,5.78,5.99,5.53,5.08,4.62,4.62,5.78,9.25,9.63,8.95,8.07,7.37,6.17,5.28,4.87,4.36,3.9,3.67,8.05,5.46

In [7]:
# Drop US unemployment columns and display head
unemployment_us = unemployment_us.drop(columns=["country_name", "country_code"])
unemployment_us.head()

,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
222,6.8,7.5,6.9,6.12,5.65,5.45,5.0,4.51,4.22,3.99,4.73,5.78,5.99,5.53,5.08,4.62,4.62,5.78,9.25,9.63,8.95,8.07,7.37,6.17,5.28,4.87,4.36,3.9,3.67,8.05,5.46

In [8]:
# Create US unemployment melt
unemployment_us_melt = unemployment_us.melt()

# Rename columns
unemployment_us_melt.rename(columns={"variable": "year", "value": "unemployment_rate"}, inplace=True)

# Display head and tail
display(unemployment_us_melt.head())
display(unemployment_us_melt.tail())

   year  unemployment_rate
0  1991               6.80
1  1992               7.50
2  1993               6.90
3  1994               6.12
4  1995               5.65

    year  unemployment_rate
26  2017               4.36
27  2018               3.90
28  2019               3.67
29  2020               8.05
30  2021               5.46

In [9]:
# Create US unemployment plot
unemployment_us_plot = unemployment_us_melt.hvplot(
    x="year",
    y="unemployment_rate",
    title="US Unemployment Rate",
    xlabel="Year",
    ylabel="Unemployment Rate",
    rot=45
)

# Display plot
unemployment_us_plot

:Curve   [year]   (unemployment_rate)